from . import start
from . import add_category
from . import add_product
from . import back_to_main_menu
from . import delete_product
from . import delete_category
from . import info
from . import last_order
from . import new_order
from . import notification